name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Wait a few secs
      uses: maddox/actions/sleep@master
      with:
        args: 10

    - name: Composer install
      uses: fireworkweb/fwd@github-actions-test
      env:
        DOCKER_HOST: ""
      with:
        args: fwd composer update --no-interaction --prefer-dist

    - name: PHPUnit
      uses: fireworkweb/fwd@github-actions-test
      with:
        args: fwd test --coverage-clover=coverage.xml

    services:
      dind:
        image: docker:dind
        ports:
        - 2375
        options: --privileged
